version: '3.8'

services:
  masterpiece-dump:
    build: ./frontend
    image: masterpiece-dump
    container_name: masterpiece-dump
    environment:
      VIRTUAL_HOST: masterpiece-dump.ru
      VIRTUAL_PORT: 80
    depends_on:
      - nginx-backend
    networks:
      - proxy-network
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php-backend
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=lib
      - DB_USER=user
      - DB_PASSWORD=user

  nginx-backend:
    image: nginx:1.29
    ports:
      - "8000:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/:/app:ro
    depends_on:
      - php
    networks:
      - app-network

  postgres:
    image: postgres:18-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=lib
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  proxy-network:
    external: true